### ISSUE TITLE
Links between Fundly and digitalnest.org

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#5]
"Donate" bounces user out of Digital NEST website to Fundly, with no way to return to Digital NEST, at least as far as I could tell…this is not great – any way to link the DN logo on the Fundly page with the DN home page?

**Comment by rskoenig** [comment]
We can also directly embed the fundly app into the NEST page - that could solve the issue...

**Comment by kirstiscott** [comment]
Is there a way to edit the description on the Fundly page to include a link back to the site? We could also install a plug-in that would make it so all external links open a new tab or window so that the DN site is still there when they close the Fundly window....

If we could embed the Fundly app on a web page on the DN site, that might solve everything. Is this something you can do or can you send me instructions?

**Comment by rskoenig** [comment]
The Fundly page has an embed link:

<div class='fundly-widget' style='width:277px;border:1px solid #D4D4D4;border-radius:3px;background:#fcfcfc;'><iframe src='https://d2wwhrh9otv6z9.cloudfront.net/campaign_card.html?activity=digital-nest-launch&hb=t' style='border:none;width:275px;height:510px'></iframe><p style='text-align:right;margin:-6px 0 0 0;padding:5px 10px;border-top:1px solid #eee;font:10px/16px helvetica !important;'><a href='https://digitalnest.fundly.com/digital-nest-launch?ft_src=widget_campaign_card' style='color:#888;margin:0;text-decoration:none;float:left'>See Jacob's Campaign</a><a href='https://fundly.com?ft_src=widget_campaign_card' style='color:#888;margin:0;text-decoration:none;' target='_blank'>Powered by Fundly</a></p></div>

**Comment by kirstiscott** [comment]
I added the embed on the home page in the announcements section instead of the same message that's already in the blog. The widget opens in a new window. If this is good with you, you can close this issue.
